import { flutedGlassFragmentShader, GlassDistortionShapes, GlassGridShapes } from "@paper-design/shaders";
import { hexToRgbTriple } from "../color/palette";
import type { CompositePreset, ShaderPreset } from "./types";
import { blob } from "./blob";

// Strip paper-design's version/precision header and align the UV varying name
// to our vertex shader's output (`v_uv` instead of `v_imageUV`).
// Also disable the frame boundary clipping — the blob FBO covers the full canvas
// so there are no out-of-bounds areas, and keeping the clamp causes hard-edged
// cutoffs when the flute pattern is rotated.
const foregroundGlsl = flutedGlassFragmentShader
  .replace("#version 300 es\nprecision mediump float;\n", "")
  .replace("in vec2 v_imageUV;\n", "")
  .replace(/\bv_imageUV\b/g, "v_uv")
  .replace("float frame = getUvFrame(uv, edgeDistortion);", "float frame = 1.0;");

function hexToVec4(hex: string, alpha = 1.0): [number, number, number, number] {
  const [r, g, b] = hexToRgbTriple(hex);
  return [r, g, b, alpha];
}

export const flutedGlass: CompositePreset = {
  kind: "composite",
  id: "fluted-glass",
  name: "Fluted Glass",
  description: "A moving blob seen through a panel of fluted glass. The glass refracts, casts shadows, and catches highlights across configurable ridge patterns.",
  backgroundPreset: blob as ShaderPreset,
  foregroundShader: foregroundGlsl,
  colorSlots: [
    { kind: "color", key: "colorBg",        label: "Background" },
    { kind: "color", key: "colorLight1",    label: "Light 1" },
    { kind: "color", key: "colorLight2",    label: "Light 2" },
    { kind: "color", key: "colorLight3",    label: "Light 3" },
    { kind: "color", key: "colorKey",       label: "Key light" },
    { kind: "color", key: "colorShadow",    label: "Glass shadow" },
  ],
  variants: [
    {
      name: "Default",
      params: {
        u_size:            0.95,
        u_angle:           30,
        u_distortion:      0.5,
        u_distortionShape: "prism",
        u_shape:           "lines",
        u_shadows:         0.25,
        u_blur:            0.7,
        u_stretch:         0,
        u_shift:           0,
        u_blob_size:       0.8,
        u_morph:           0.5,
        u_speed:           0.7,
        u_elongate:        0.25,
        u_grain:           0,
        u_vignette:        0.6,
        u_seed:            1.7,
        colorBg:           "#050308",
        colorLight1:       "#0000FF",
        colorLight2:       "#ff0000",
        colorLight3:       "#ff0000",
        colorKey:          "#ffffff",
        colorShadow:       "#000000",
      },
    },
    {
      name: "Velvet",
      params: {
        u_size:            0.91,
        u_angle:           0,
        u_distortion:      0.69,
        u_distortionShape: "prism",
        u_shape:           "lines",
        u_shadows:         0.33,
        u_blur:            0.7,
        u_stretch:         0,
        u_shift:           0,
        u_blob_size:       0.87,
        u_key_strength:    2,
        u_blob_brightness: 3,
        u_bg_brightness:   0,
        u_light_radius:    0.42,
        u_morph:           0.5,
        u_speed:           0.7,
        u_elongate:        0.25,
        u_grain:           0.05,
        u_vignette:        0.28,
        u_seed:            1.7,
        colorBg:           "#27616d",
        colorLight1:       "#7703fc",
        colorLight2:       "#ab62fd",
        colorLight3:       "#7703fc",
        colorKey:          "#7703fc",
        colorShadow:       "#143238",
      },
    },
    {
      name: "Cappuccino",
      params: {
        u_size:            0.95,
        u_angle:           30,
        u_distortion:      0.5,
        u_distortionShape: "contour",
        u_shape:           "wave",
        u_shadows:         0.25,
        u_blur:            1,
        u_stretch:         0.2,
        u_shift:           0,
        u_blob_size:       0.8,
        u_morph:           0.5,
        u_speed:           1.15,
        u_elongate:        0.24,
        u_grain:           0,
        u_vignette:        0.6,
        u_seed:            1.7,
        colorBg:           "#211912",
        colorLight1:       "#A47864",
        colorLight2:       "#503a2f",
        colorLight3:       "#FFBE98",
        colorKey:          "#F0EEE9",
        colorShadow:       "#000000",
      },
    },
  ],
  schema: [
    // Glass
    { kind: "range",  key: "u_size",             label: "Flute width",     min: 0,    max: 1,    step: 0.01,  default: 0.5 },
    { kind: "range",  key: "u_angle",             label: "Flute angle",     min: 0,    max: 180,  step: 1,     default: 0 },
    { kind: "range",  key: "u_distortion",        label: "Distortion",      min: 0,    max: 1,    step: 0.01,  default: 0.5 },
    { kind: "select", key: "u_distortionShape",   label: "Distortion type",
      options: [
        { value: "prism",    label: "Prism" },
        { value: "lens",     label: "Lens" },
        { value: "contour",  label: "Contour" },
        { value: "cascade",  label: "Cascade" },
        { value: "flat",     label: "Flat" },
      ],
      default: "prism",
    },
    { kind: "select", key: "u_shape",             label: "Grid pattern",
      options: [
        { value: "lines",          label: "Lines" },
        { value: "linesIrregular", label: "Irregular" },
        { value: "wave",           label: "Wave" },
        { value: "zigzag",         label: "Zigzag" },
      ],
      default: "lines",
    },
    { kind: "range",  key: "u_shadows",           label: "Shadows",         min: 0,    max: 1,    step: 0.01,  default: 0.25 },
    { kind: "range",  key: "u_blur",              label: "Blur",            min: 0,    max: 1,    step: 0.01,  default: 0 },
    { kind: "range",  key: "u_stretch",           label: "Stretch",         min: 0,    max: 1,    step: 0.01,  default: 0 },
    { kind: "range",  key: "u_shift",             label: "Shift",           min: -1,   max: 1,    step: 0.01,  default: 0 },
    // Blob
    { kind: "range",  key: "u_blob_size",         label: "Blob size",       min: 0.30, max: 0.90, step: 0.01,  default: 0.80 },
    { kind: "range",  key: "u_key_strength",      label: "Key brightness",  min: 0,    max: 2.00, step: 0.05,  default: 1.20 },
    { kind: "range",  key: "u_blob_brightness",   label: "Light brightness", min: 0.1,  max: 3.00, step: 0.05,  default: 0.50 },
    { kind: "range",  key: "u_bg_brightness",     label: "Background bleed", min: 0,    max: 0.80, step: 0.01,  default: 0.21 },
    { kind: "range",  key: "u_light_radius",      label: "Light spread",     min: 0.20, max: 1.80, step: 0.01,  default: 0.40 },
    { kind: "range",  key: "u_morph",             label: "Morph",           min: 0,    max: 2.00, step: 0.01,  default: 1.08 },
    { kind: "range",  key: "u_speed",             label: "Speed",           min: 0,    max: 2.50, step: 0.05,  default: 0.80 },
    { kind: "range",  key: "u_elongate",          label: "Elongation",      min: 0,    max: 0.70, step: 0.01,  default: 0.25 },
    // Shared
    { kind: "range",  key: "u_grain",             label: "Grain",           min: 0,    max: 0.5,  step: 0.01,  default: 0 },
    { kind: "range",  key: "u_vignette",          label: "Vignette",        min: 0,    max: 0.60, step: 0.02,  default: 0.24 },
    { kind: "seed",   key: "u_seed",              label: "Seed",                                              default: 1.7 },
  ],
  defaults: {
    u_size:            0.5,
    u_angle:           0,
    u_distortion:      0.5,
    u_distortionShape: "prism",
    u_shape:           "lines",
    u_shadows:         0.25,
    u_blur:            0,
    u_stretch:         0,
    u_shift:           0,
    u_blob_size:       0.80,
    u_key_strength:    1.20,
    u_blob_brightness: 1.00,
    u_bg_brightness:   0.21,
    u_light_radius:    0.40,
    u_morph:           1.08,
    u_speed:           0.80,
    u_elongate:        0.25,
    u_grain:           0,
    u_vignette:        0.24,
    u_seed:            1.7,
    colorBg:           "#050308",
    colorLight1:       "#4a6dff",
    colorLight2:       "#8b3ee0",
    colorLight3:       "#ff6b94",
    colorKey:          "#ffffff",
    colorShadow:       "#000000",
  },
  backgroundUniforms: (params) => ({
    u_size:            params.u_blob_size   as number,
    u_elongate:        params.u_elongate    as number,
    u_morph:           params.u_morph       as number,
    u_blur:            0.050,
    u_blur_var:        1.00,
    u_light_radius:    params.u_light_radius as number,
    u_key_radius:      0.32,
    u_key_strength:    params.u_key_strength as number,
    u_bg_brightness:   params.u_bg_brightness as number,
    u_blob_brightness: params.u_blob_brightness as number,
    u_speed:           params.u_speed       as number,
    u_grain:           0,
    u_vignette:        params.u_vignette    as number,
    u_seed:            params.u_seed        as number,
    u_color_bg:        hexToRgbTriple(typeof params.colorBg     === "string" ? params.colorBg     : "#050308"),
    u_color_light1:    hexToRgbTriple(typeof params.colorLight1 === "string" ? params.colorLight1 : "#4a6dff"),
    u_color_light2:    hexToRgbTriple(typeof params.colorLight2 === "string" ? params.colorLight2 : "#8b3ee0"),
    u_color_light3:    hexToRgbTriple(typeof params.colorLight3 === "string" ? params.colorLight3 : "#ff6b94"),
    u_color_key:       hexToRgbTriple(typeof params.colorKey    === "string" ? params.colorKey    : "#ffffff"),
  }),
  foregroundUniforms: (params) => ({
    u_size:            params.u_size        as number,
    u_angle:           params.u_angle       as number,
    u_distortion:      params.u_distortion  as number,
    u_distortionShape: GlassDistortionShapes[params.u_distortionShape as keyof typeof GlassDistortionShapes] ?? 1,
    u_shape:           GlassGridShapes[params.u_shape as keyof typeof GlassGridShapes] ?? 1,
    u_shadows:         params.u_shadows     as number,
    u_highlights:      0,
    u_blur:            params.u_blur        as number,
    u_stretch:         params.u_stretch     as number,
    u_shift:           params.u_shift       as number,
    u_rotation:        0,
    u_edges:           0,
    u_grainMixer:      0,
    u_grainOverlay:    params.u_grain       as number,
    u_marginLeft:      0,
    u_marginRight:     0,
    u_marginTop:       0,
    u_marginBottom:    0,
    u_colorBack:       hexToVec4(typeof params.colorBg === "string" ? params.colorBg : "#050308"),
    u_colorHighlight:  [1, 1, 1, 1],
    u_colorShadow:     hexToVec4(typeof params.colorShadow === "string" ? params.colorShadow : "#000000"),
  }),
};
